import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { assert } from "chai";
import { Keypair, SystemProgram, PublicKey } from "@solana/web3.js";
import { createHash } from "crypto";

// ZkPox IDL type is auto-generated by `anchor build`.
// Before first build, we use `any` to avoid IDE type errors.
// After `anchor build`, replace with: import { ZkPox } from "../target/types/zk_pox";
type ZkPox = any;

describe("zk-pox", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.ZkPox as Program;

  const agent = Keypair.generate();
  const witness1 = Keypair.generate();
  const witness2 = Keypair.generate();

  const credentialId = createHash("sha256")
    .update("test-credential-001")
    .digest();

  const proofHash = createHash("sha256")
    .update("fake-bulletproof-bytes")
    .digest();

  const publicInputsHash = createHash("sha256")
    .update("center_hash|200|30|10|15")
    .digest();

  const commitmentsHash = createHash("sha256")
    .update("fake-pedersen-commitments")
    .digest();

  let credentialPda: PublicKey;
  let credentialBump: number;

  before(async () => {
    // Airdrop SOL to agent and witnesses
    const airdropAgent = await provider.connection.requestAirdrop(
      agent.publicKey,
      2 * anchor.web3.LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdropAgent);

    const airdropW1 = await provider.connection.requestAirdrop(
      witness1.publicKey,
      1 * anchor.web3.LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdropW1);

    const airdropW2 = await provider.connection.requestAirdrop(
      witness2.publicKey,
      1 * anchor.web3.LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdropW2);

    // Derive credential PDA
    [credentialPda, credentialBump] = PublicKey.findProgramAddressSync(
      [
        Buffer.from("credential"),
        agent.publicKey.toBuffer(),
        credentialId,
      ],
      program.programId
    );
  });

  // ───────────────────────────────────────────────────
  // submit_credential
  // ───────────────────────────────────────────────────

  it("submit_credential — creates on-chain credential", async () => {
    const tx = await program.methods
      .submitCredential(
        Array.from(credentialId) as any,
        0, // RESIDENCY
        Array.from(proofHash) as any,
        Array.from(publicInputsHash) as any,
        Array.from(commitmentsHash) as any,
        15 // count_proven
      )
      .accounts({
        agent: agent.publicKey,
        credential: credentialPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([agent])
      .rpc();

    const credential = await program.account["experienceCredential"].fetch(
      credentialPda
    );

    assert.equal(credential.version, 2);
    assert.deepEqual(
      Array.from(credential.agentId),
      Array.from(agent.publicKey.toBytes())
    );
    assert.equal(credential.claimType, 0);
    assert.deepEqual(Array.from(credential.proofHash), Array.from(proofHash));
    assert.deepEqual(
      Array.from(credential.publicInputsHash),
      Array.from(publicInputsHash)
    );
    assert.deepEqual(
      Array.from(credential.commitmentsHash),
      Array.from(commitmentsHash)
    );
    assert.equal(credential.countProven, 15);
    assert.equal(credential.witnessCount, 0);
    assert.equal(credential.revoked, false);
    assert.ok(credential.issuedAt.toNumber() > 0);
  });

  it("submit_credential — rejects invalid claim_type > 5", async () => {
    const badCredId = createHash("sha256")
      .update("bad-claim-type")
      .digest();

    const [badPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("credential"), agent.publicKey.toBuffer(), badCredId],
      program.programId
    );

    try {
      await program.methods
        .submitCredential(
          Array.from(badCredId) as any,
          6, // invalid
          Array.from(proofHash) as any,
          Array.from(publicInputsHash) as any,
          Array.from(commitmentsHash) as any,
          10
        )
        .accounts({
          agent: agent.publicKey,
          credential: badPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();
      assert.fail("should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "InvalidClaimType");
    }
  });

  it("submit_credential — rejects count_proven = 0", async () => {
    const zeroCredId = createHash("sha256")
      .update("zero-count")
      .digest();

    const [zeroPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("credential"), agent.publicKey.toBuffer(), zeroCredId],
      program.programId
    );

    try {
      await program.methods
        .submitCredential(
          Array.from(zeroCredId) as any,
          0,
          Array.from(proofHash) as any,
          Array.from(publicInputsHash) as any,
          Array.from(commitmentsHash) as any,
          0 // invalid
        )
        .accounts({
          agent: agent.publicKey,
          credential: zeroPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();
      assert.fail("should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "InvalidCountProven");
    }
  });

  // ───────────────────────────────────────────────────
  // add_witness
  // ───────────────────────────────────────────────────

  it("add_witness — witness1 attests", async () => {
    await program.methods
      .addWitness()
      .accounts({
        witness: witness1.publicKey,
        credential: credentialPda,
      })
      .signers([witness1])
      .rpc();

    const credential = await program.account["experienceCredential"].fetch(
      credentialPda
    );

    assert.equal(credential.witnessCount, 1);
    assert.deepEqual(
      Array.from(credential.witnesses[0]),
      Array.from(witness1.publicKey.toBytes())
    );
  });

  it("add_witness — witness2 attests", async () => {
    await program.methods
      .addWitness()
      .accounts({
        witness: witness2.publicKey,
        credential: credentialPda,
      })
      .signers([witness2])
      .rpc();

    const credential = await program.account["experienceCredential"].fetch(
      credentialPda
    );

    assert.equal(credential.witnessCount, 2);
    assert.deepEqual(
      Array.from(credential.witnesses[1]),
      Array.from(witness2.publicKey.toBytes())
    );
  });

  it("add_witness — rejects duplicate witness", async () => {
    try {
      await program.methods
        .addWitness()
        .accounts({
          witness: witness1.publicKey,
          credential: credentialPda,
        })
        .signers([witness1])
        .rpc();
      assert.fail("should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "AlreadyWitnessed");
    }
  });

  // ───────────────────────────────────────────────────
  // revoke_credential
  // ───────────────────────────────────────────────────

  it("revoke_credential — rejects non-owner", async () => {
    try {
      await program.methods
        .revokeCredential()
        .accounts({
          agent: witness1.publicKey, // not the owner
          credential: credentialPda,
        })
        .signers([witness1])
        .rpc();
      assert.fail("should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "Unauthorized");
    }
  });

  it("revoke_credential — owner revokes", async () => {
    await program.methods
      .revokeCredential()
      .accounts({
        agent: agent.publicKey,
        credential: credentialPda,
      })
      .signers([agent])
      .rpc();

    const credential = await program.account["experienceCredential"].fetch(
      credentialPda
    );

    assert.equal(credential.revoked, true);
  });

  it("revoke_credential — rejects double revoke", async () => {
    try {
      await program.methods
        .revokeCredential()
        .accounts({
          agent: agent.publicKey,
          credential: credentialPda,
        })
        .signers([agent])
        .rpc();
      assert.fail("should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "CredentialRevoked");
    }
  });

  it("add_witness — rejects on revoked credential", async () => {
    const witness3 = Keypair.generate();
    const airdrop = await provider.connection.requestAirdrop(
      witness3.publicKey,
      1 * anchor.web3.LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdrop);

    try {
      await program.methods
        .addWitness()
        .accounts({
          witness: witness3.publicKey,
          credential: credentialPda,
        })
        .signers([witness3])
        .rpc();
      assert.fail("should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "CredentialRevoked");
    }
  });

  // ───────────────────────────────────────────────────
  // all claim types
  // ───────────────────────────────────────────────────

  it("submit_credential — all 6 claim types (0-5) succeed", async () => {
    const claimNames = [
      "RESIDENCY",
      "COMMUTE",
      "ATTENDANCE",
      "ABSENCE",
      "STABILITY",
      "TRAVEL",
    ];

    for (let i = 0; i < 6; i++) {
      const id = createHash("sha256")
        .update(`claim-type-${claimNames[i]}`)
        .digest();

      const [pda] = PublicKey.findProgramAddressSync(
        [Buffer.from("credential"), agent.publicKey.toBuffer(), id],
        program.programId
      );

      await program.methods
        .submitCredential(
          Array.from(id) as any,
          i,
          Array.from(proofHash) as any,
          Array.from(publicInputsHash) as any,
          Array.from(commitmentsHash) as any,
          10
        )
        .accounts({
          agent: agent.publicKey,
          credential: pda,
          systemProgram: SystemProgram.programId,
        })
        .signers([agent])
        .rpc();

      const credential = await program.account["experienceCredential"].fetch(pda);
      assert.equal(credential.claimType, i, `claim type ${claimNames[i]}`);
    }
  });
});
